---
abstract: 'Perl module for rewrite die by err from Error::Pure module.'
author:
  - 'Michal Spacek <skim@cpan.org>'
build_requires:
  English: 0
  Error::Pure::Utils: 0.22
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
  Test::NoWarnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Error-Pure-Always
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Error::Pure: 0.22
  perl: 5.6.0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Error-Pure-Always
  homepage: https://github.com/michal-josef-spacek/Error-Pure-Always
  license: http://opensource.org/licenses/bsd-license.php
  repository: git://github.com/michal-josef-spacek/Error-Pure-Always
version: '0.07'
